renderer:
  source:
    whistle:
      trim: true
    harmonic:
      panpipes: true
      trim: true
      source_colour: attenuated_pink
      attenuation_constant: 0
    noise:
      source_colour: pink
      band: []
      trim: true
  steps:
    t: 0.02
    f: 0.3
    scale: ERB
  cholesky_stability:
    long_duration: 1.6
    spectrum:
      basic: 0.01
      add_to_long_sounds: 0
    f0:
      basic: 0.001
      add_to_long_sounds: 0
    amplitude:
      basic: 0.001
      add_to_long_sounds: 0
  ramp_duration: 0.0184
  lo_lim_freq: 20.0
  tf:
    rms_ref: 1.0e-06
    representation: cgm
    ramp: 0.01
    gtg_params:
      rep: gtg
      twin: 0.025
      thop: 0.01
      nfilts: 64
      fmin: 20
      width: 0.5
      log_constant: 1.0e-80
      dB_threshold: 20
      ref: 1.0e-06
    cgm_params:
      rep: cgm
      ref: 1.0e-06
      pad_factor: 2
      use_rfft: true
      half_cos_filter_kwargs:
        n: 40
        low_lim: 20
        high_lim: 8000
        sample_factor: 1
        no_lowpass: true
        no_highpass: true
        full_filter: false
      hann_downsampling_kwargs:
        env_sr: 10000
        window_size: 8
        padding: 3
      sk_downsampling_kwargs:
        env_sr: 200
        window_size: 499
      compression_type: log
      compression_kwargs:
        power: 0.3
        offset: 1.0e-08
        scale: 1
        clip_value: 5
      rel_threshold: 60
      abs_threshold: 20
hyperpriors:
  n_sources:
    dist: poisson
    args: 2.5
  source_type:
    dist: uniform_categorical
    args: &id004
    - whistle
    - noise
    - harmonic
  n_events:
    dist: geometric
    args: 0.3
  gap:
    precision:
      dist: gamma
      args:
      - 2.5
      - 0.8
    mu:
      dist: normal
      args:
      - -1.5
      - 0.5
  duration:
    precision:
      dist: gamma
      args:
      - 2.5
      - 0.8
    mu:
      dist: normal
      args:
      - -1.0
      - 0.5
  whistle:
    f0: &id002
      mu:
        dist: uniform
        args:
        - 3.0
        - 33.19
      kernel:
        parametrization:
        - sigma
        - sigma_within
        - scale
        type: SE
        sigma:
          dist: uniform
          args:
          - 0.1
          - 15
        sigma_within:
          dist: uniform
          args:
          - 0
          - 3
        scale:
          dist: log_uniform
          args:
          - 0.05
          - 5.0
        epsilon:
          dist: constant
          args: 0.1
      feature: &id001
        learn_inducing_locations: true
    amplitude:
      mu:
        dist: uniform
        args:
        - 30.0
        - 100.0
      kernel:
        parametrization:
        - sigma
        - sigma_within
        - scale
        type: SE
        sigma:
          dist: uniform
          args:
          - 1.0
          - 35.0
        sigma_within:
          dist: uniform
          args:
          - 0
          - 3
        scale:
          dist: log_uniform
          args:
          - 0.05
          - 5.0
        epsilon:
          dist: constant
          args: 0.1
      feature: *id001
  harmonic:
    f0: *id002
    amplitude:
      mu:
        dist: uniform
        args:
        - 20.0
        - 80.0
      kernel:
        parametrization:
        - sigma
        - sigma_within
        - scale
        type: SE
        sigma:
          dist: uniform
          args:
          - 1.0
          - 30.0
        sigma_within:
          dist: uniform
          args:
          - 1.0e-10
          - 5.0
        scale:
          dist: log_uniform
          args:
          - 0.05
          - 5.0
        epsilon:
          dist: constant
          args: 0.54
      feature: *id001
    spectrum:
      mu:
        dist: constant
        args: 0.0
      kernel:
        parametrization:
        - sigma
        - scale
        type: SE
        sigma:
          dist: uniform
          args:
          - 1.0e-10
          - 35.0
        scale:
          dist: uniform
          args:
          - 0.5
          - 33.0
        epsilon:
          dist: constant
          args: 0.43
      feature: *id001
  noise:
    amplitude:
      mu:
        dist: uniform
        args:
        - 0.0
        - 60.0
      kernel:
        parametrization:
        - sigma
        - sigma_within
        - scale
        type: SE
        sigma:
          dist: uniform
          args:
          - 1.0
          - 30.0
        sigma_within:
          dist: uniform
          args:
          - 0.0
          - 5.0
        scale:
          dist: log_uniform
          args:
          - 0.05
          - 5.0
        epsilon:
          dist: constant
          args: 0.47
      feature: *id001
    spectrum: &id003
      mu:
        dist: constant
        args: 0.0
      kernel:
        parametrization:
        - sigma
        - scale
        type: SE
        sigma:
          dist: uniform
          args:
          - 1.0
          - 35.0
        scale:
          dist: uniform
          args:
          - 0.5
          - 33.0
        epsilon:
          dist: constant
          args: 0.66
      feature: *id001
dream:
  n_chunks: 9999
  chunk_size: 5
  audio_sr: 20000
  silence_threshold: 15
  tf_representation:
  - gtg
  - cgm
  dur:
  - 0.5
  - 4.0
  event_features:
    timing: *id004
    f0:
    - whistle
    - harmonic
    amplitude:
    - whistle
    spa:
    - harmonic
    - noise